//! Flight-control policies, kept independent from the simulator and UI.

use light_robot_core_simulation::{ControlInputs, ControlSystem, Quat, SensorData, Vec3};

pub struct PidControlSystem { pub p_gain: f32, pub i_gain: f32, pub d_gain: f32, last_time: f32, integral: [f32; 2], rotation: Quat }
impl PidControlSystem { pub fn new(p: f32, i: f32, d: f32) -> Self { Self { p_gain: p, i_gain: i, d_gain: d, last_time: 0.0, integral: [0.0; 2], rotation: Quat::IDENTITY } } }
impl PidControlSystem {
    /// Seeds the estimator for simulation/HIL runs, where the simulated
    /// vehicle attitude is known at t=0 instead of coming from a real IMU.
    pub fn set_estimated_rotation(&mut self, rotation: Quat) { self.rotation = rotation; }
}
fn deviation(rotation: Quat) -> [f32; 2] { let direction = rotation.conjugate().rotate(Vec3::UP); let length = (direction.x*direction.x + direction.y*direction.y).sqrt(); if length < 1e-6 { [0.0; 2] } else { let angle = direction.z.clamp(-1.0, 1.0).acos(); [direction.x / length * angle, direction.y / length * angle] } }
impl ControlSystem for PidControlSystem { fn reset(&mut self) { self.last_time = 0.0; self.integral = [0.0; 2]; self.rotation = Quat::IDENTITY; } fn update(&mut self, sensor: &SensorData) -> ControlInputs { let dt = (sensor.time - self.last_time).max(0.0); self.last_time = sensor.time; let q_dot = self.rotation * Quat { x: sensor.angular_velocity.x, y: sensor.angular_velocity.y, z: sensor.angular_velocity.z, w: 0.0 } * 0.5; self.rotation = (self.rotation + q_dot * dt).normalized(); let d = deviation(self.rotation); self.integral[0] = (self.integral[0] - d[1] * dt).clamp(-1.0, 1.0); self.integral[1] = (self.integral[1] + d[0] * dt).clamp(-1.0, 1.0); ControlInputs { tvc: [(-d[1]*self.p_gain - sensor.angular_velocity.x*self.d_gain + self.integral[0]*self.i_gain).clamp(-1.0,1.0), (d[0]*self.p_gain - sensor.angular_velocity.y*self.d_gain + self.integral[1]*self.i_gain).clamp(-1.0,1.0)], ignition: true, parachute: false } } }

/// Feed-forward network format retained from the previous neural-control work.
#[derive(Clone, Debug)]
pub struct NeuralNetwork { pub layers: Vec<usize>, pub parameters: Vec<f32> }
impl NeuralNetwork { pub fn parameter_count(layers: &[usize]) -> usize { layers.windows(2).map(|pair| pair[1] * (pair[0] + 1)).sum() } pub fn calculate(&self, input: &[f32]) -> Option<Vec<f32>> { if self.layers.first().copied()? != input.len() || self.parameters.len() != Self::parameter_count(&self.layers) { return None; } let mut previous = input.to_vec(); let mut index = 0; for &width in &self.layers[1..] { let mut current = Vec::with_capacity(width); for _ in 0..width { let mut value = 0.0; for input in &previous { value += *input * self.parameters[index]; index += 1; } value += self.parameters[index]; index += 1; current.push(value / (1.0 + value.abs())); } previous = current; } Some(previous) } }
pub struct NeuralControlSystem<'a> { pub network: &'a NeuralNetwork, memory: [f32; 2], last_time: f32, rotation: Quat }
impl<'a> NeuralControlSystem<'a> { pub fn new(network: &'a NeuralNetwork) -> Self { Self { network, memory: [0.0;2], last_time: 0.0, rotation: Quat::IDENTITY } } }
impl ControlSystem for NeuralControlSystem<'_> { fn reset(&mut self) { self.memory = [0.0;2]; self.last_time = 0.0; self.rotation = Quat::IDENTITY; } fn update(&mut self, sensor: &SensorData) -> ControlInputs { let dt = (sensor.time-self.last_time).max(0.0); self.last_time=sensor.time; let q_dot=self.rotation*Quat{x:sensor.angular_velocity.x,y:sensor.angular_velocity.y,z:sensor.angular_velocity.z,w:0.0}*0.5; self.rotation=(self.rotation+q_dot*dt).normalized(); let d=deviation(self.rotation); let x=self.network.calculate(&[-d[1],sensor.angular_velocity.x,self.memory[0]]).unwrap_or_default(); let xn=self.network.calculate(&[d[1],-sensor.angular_velocity.x,-self.memory[0]]).unwrap_or_default(); let y=self.network.calculate(&[d[0],sensor.angular_velocity.y,self.memory[1]]).unwrap_or_default(); let yn=self.network.calculate(&[-d[0],-sensor.angular_velocity.y,-self.memory[1]]).unwrap_or_default(); let output=[x.get(0).copied().unwrap_or(0.0)-xn.get(0).copied().unwrap_or(0.0), y.get(0).copied().unwrap_or(0.0)-yn.get(0).copied().unwrap_or(0.0)]; self.memory=[x.get(1).copied().unwrap_or(0.0)-xn.get(1).copied().unwrap_or(0.0),y.get(1).copied().unwrap_or(0.0)-yn.get(1).copied().unwrap_or(0.0)]; ControlInputs{tvc:[output[0].clamp(-1.0,1.0),output[1].clamp(-1.0,1.0)],ignition:true,parachute:false} } }
