[package]
name = "light-robot-core-frontend"
version = "0.0.1"
edition = "2021"

[profile.release]
opt-level = "s"
strip = true
lto = true
codegen-units = 1

[dependencies]
light-robot-core-api = {path = "../light-robot-core-api"}
light-robot-core-simulation = {path = "../light-robot-core-simulation"}
light-robot-core-flight-control = {path = "../light-robot-core-flight-control"}

yew = { version = "0.20", features = ["csr"] }
#yew-mdc = {git = "https://github.com/lukepfeiffer10/yew-mdc.git"}
yew-hooks = "0.2.0"
material-yew = { version = "0.3.0", features = ["full"] }
web-sys = { version = "0.3.104", features = ["CanvasRenderingContext2d", "DomRect", "Element", "HtmlCanvasElement", "HtmlInputElement", "HtmlSelectElement", "KeyboardEvent"] }
reqwasm = "0.5.0"
wasm-bindgen = "0.2.127"
wasm-bindgen-futures = "0.4.77"
serde = "1.0.229"
serde_json = "1.0.149"
gloo = "0.12.0"
gloo-timers = { version = "0.4.0", features = ["futures"] }
