use serde::{Deserialize, Serialize};

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct State {
    pub battery: BatteryState,
    pub pyro: PyroState,
    pub wifi_state: WifiConnectionConfiguration,
    /// SSID saved for the next boot. The password is deliberately never sent
    /// over the HTTP or WebSocket state APIs.
    pub configured_wifi_ssid: String,
    pub barometer: BarometerState,
    pub imu: ImuState,
    pub inertia_capture: InertiaCaptureState,
    pub inertia_configuration: InertiaConfiguration,
    /// Parameters for the browser-side flight-model preview.  Vehicle mass,
    /// inertia and the gimbal-to-COM distance deliberately live in
    /// `inertia_configuration`, since they are measured during onboarding.
    pub simulation_configuration: SimulationConfiguration,
    #[serde(default)] pub hil_simulation: HilSimulationState,
    pub servo1: ServoState,
    pub servo2: ServoState,
    pub weight: i32,
    pub chip_id1: [u8; 6],
    pub chip_id2: [u8; 6],
    pub servo_calibration: ServoCalibrationState,
}

#[derive(Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum ServoAxis {
    X,
    Y,
}

/// The two 48-bit identity halves reported by a servo during CAN discovery.
#[derive(Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct ServoDeviceId {
    pub chip_id1: [u8; 6],
    pub chip_id2: [u8; 6],
}

impl Default for ServoAxis {
    fn default() -> Self {
        Self::X
    }
}

#[derive(Clone, PartialEq, Serialize, Deserialize)]
pub struct ServoConfiguration {
    /// Encoder counts at the mechanically defined TVC zero position.
    pub zero_encoder_count: u16,
    /// Physical deflection represented by command -1.0 / +1.0, in degrees.
    pub max_turn_degrees: f32,
    pub position_p: f32,
    pub position_i: f32,
    pub position_d: f32,
    pub duty_cycle_limit: f32,
    /// Reverses the brushed H-bridge polarity for this physical motor.
    pub reverse_motor: bool,
    /// Reverses this axis at the flight-controller level, without changing
    /// servo firmware or motor wiring.
    #[serde(default)]
    pub reverse_control: bool,
}

impl Default for ServoConfiguration {
    fn default() -> Self {
        Self {
            zero_encoder_count: 0,
            max_turn_degrees: 10.0,
            position_p: 0.02,
            position_i: 0.0,
            position_d: 0.0,
            duty_cycle_limit: 0.75,
            reverse_motor: false,
            reverse_control: false,
        }
    }
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ServoCalibrationState {
    pub x: ServoConfiguration,
    pub y: ServoConfiguration,
    pub x_enabled: bool,
    pub y_enabled: bool,
    pub detected_x: bool,
    pub detected_y: bool,
    pub test_running: bool,
    /// True while the gravity-vector TVC orientation check owns both servos.
    #[serde(default)]
    pub orientation_check_running: bool,
    /// Latest normalized commands generated by the orientation check.
    #[serde(default)]
    pub orientation_check_command: [f32; 2],
    /// Devices found by the latest CAN discovery scan.
    pub discovered_devices: Vec<ServoDeviceId>,
    /// The device currently assigned to each TVC axis, if any.
    pub x_device: Option<ServoDeviceId>,
    pub y_device: Option<ServoDeviceId>,
    pub test_result_revision: u32,
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ServoTestSample {
    /// Capture timestamp relative to the commanded step, in microseconds.
    pub time_us: u32,
    pub position: f32,
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ServoTestResult {
    pub axis: ServoAxis,
    pub configuration: ServoConfiguration,
    pub samples: Vec<ServoTestSample>,
}

/// Messages carried by the persistent UI WebSocket.
#[derive(Clone, PartialEq, Serialize, Deserialize)]
pub enum SocketMessage {
    State(State),
    TestResult(ServoTestResult),
    InertiaCaptureResult(InertiaCaptureResult),
    HilSimulationChunk(HilSimulationChunk),
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ServoState {
    pub position: u16,
    pub velocity: i16,
    pub current: i16,
    pub sensor_detected: bool,
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct BatteryState {
    pub present: bool,
    pub soc: f32,
    pub voltage: f32,
    pub charge_rate: f32,
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize, Debug)]
pub struct WifiCredentials {
    pub ssid: String,
    pub password: String,
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize, Debug)]
pub struct WifiConnectionConfiguration {
    pub connection_type: WifiConnectionType,
    pub credentials: WifiCredentials,
}

#[derive(Clone, PartialEq, Serialize, Deserialize, Debug)]
pub enum WifiConnectionType {
    ConnectToExternal,
    StartAccessPoint,
}

impl Default for WifiConnectionType {
    fn default() -> Self {
        WifiConnectionType::StartAccessPoint
    }
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PyroChannelState {
    pub fire: bool,
    pub test_voltage: f32,
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PyroState {
    pub channel1: PyroChannelState,
    pub channel2: PyroChannelState,
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct BarometerState {
    pub altitude: f32,
    pub temperature: f32,
}

/// Latest raw inertial measurement from the board-mounted ICM-42688-P.
///
/// Acceleration is expressed in m/s² and angular velocity in rad/s, using the
/// ICM-42688-P's configured ±16 g and ±2000 °/s ranges respectively. The axes are
/// the physical sensor axes; board-to-vehicle alignment is intentionally not
/// applied here.
#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ImuState {
    pub present: bool,
    pub acceleration_mps2: [f32; 3],
    pub angular_velocity_radps: [f32; 3],
    /// Monotonically wrapping count of successful 100 Hz samples.
    pub sample_count: u32,
    /// Average successful host acquisition rate since the last IMU initialization.
    pub average_rate_hz: f32,
}

#[derive(Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum InertiaAxis {
    X,
    Y,
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct InertiaCaptureState {
    pub running: bool,
    pub result_revision: u32,
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct InertiaGyroSample {
    /// Timestamp relative to capture start, in microseconds.
    pub time_us: u32,
    pub gyro_x_radps: f32,
    pub gyro_y_radps: f32,
}

/// A five-second pendulum capture used to determine the rotation axis and
/// later calculate the vehicle's moment of inertia.
#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct InertiaCaptureResult {
    pub dominant_axis: Option<InertiaAxis>,
    pub measured_rate_hz: f32,
    pub samples: Vec<InertiaGyroSample>,
}

#[derive(Clone, PartialEq, Serialize, Deserialize)]
pub struct InertiaConfiguration {
    pub mass_g: f32,
    /// Distance from the suspension axis to the rocket center of mass.
    pub center_of_mass_offset_mm: f32,
    /// Principal moments around the board/rocket X, Y, and Z axes, in kg·m².
    pub moment_of_inertia_kgm2: [f32; 3],
}

/// Tunable inputs to the onboarding flight simulation.
///
/// Units are SI except where a field explicitly says degrees or milliseconds.
/// This is a data-only type: the simulation crate turns it, together with the
/// measured `InertiaConfiguration`, into a physical model.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum MotorThrustProfile {
    /// A rectangular pulse using the configured thrust and burn duration.
    Constant,
    /// Raketenmodellbau Klima D3 manufacturer RASP data.
    KlimaD3,
}

impl Default for MotorThrustProfile {
    fn default() -> Self { Self::Constant }
}

#[derive(Clone, PartialEq, Serialize, Deserialize)]
pub struct SimulationConfiguration {
    /// Defaults to `Constant` so configurations saved before profiles existed
    /// remain readable from flash.
    #[serde(default)]
    pub motor_thrust_profile: MotorThrustProfile,
    pub thrust_newtons: f32,
    pub burn_time_s: f32,
    pub max_tvc_angle_degrees: f32,
    pub max_tvc_rate_degrees_per_s: f32,
    pub tvc_delay_ms: u16,
    pub tvc_misalignment_degrees: [f32; 2],
    pub drag_coefficient_axial: f32,
    pub drag_coefficient_sideways: f32,
    /// Reference area in square metres.
    pub reference_area_m2: f32,
    pub center_of_pressure_offset_mm: f32,
    pub wind_mps: [f32; 3],
    pub initial_tilt_degrees: [f32; 2],
    pub pid_gains: [f32; 3],
}
#[derive(Clone, PartialEq, Default, Serialize, Deserialize)] pub struct HilSimulationState { pub running: bool, pub result_revision: u32, pub missed_deadlines: u32 }
#[derive(Clone, PartialEq, Default, Serialize, Deserialize)] pub struct HilSimulationSample { pub time_us: u32, pub scheduled_time_us: u32, pub position_m: [f32; 3], pub orientation_xy_degrees: [f32; 2], pub tvc_command: [f32; 2], pub tvc_actual: [f32; 2] }
#[derive(Clone, PartialEq, Default, Serialize, Deserialize)] pub struct HilSimulationResult { pub samples: Vec<HilSimulationSample>, pub missed_deadlines: u32 }
#[derive(Clone, PartialEq, Default, Serialize, Deserialize)] pub struct HilSimulationChunk { pub revision: u32, pub index: u16, pub total: u16, pub missed_deadlines: u32, pub samples: Vec<HilSimulationSample> }

impl Default for SimulationConfiguration {
    fn default() -> Self {
        Self {
            motor_thrust_profile: MotorThrustProfile::Constant,
            thrust_newtons: 3.0,
            burn_time_s: 5.0,
            max_tvc_angle_degrees: 5.0,
            max_tvc_rate_degrees_per_s: 286.5,
            tvc_delay_ms: 20,
            tvc_misalignment_degrees: [0.0; 2],
            drag_coefficient_axial: 0.2,
            drag_coefficient_sideways: 1.2,
            reference_area_m2: 0.01,
            center_of_pressure_offset_mm: 50.0,
            wind_mps: [0.0; 3],
            initial_tilt_degrees: [3.0, 0.0],
            pid_gains: [2.0, 2.0, 0.8],
        }
    }
}

impl Default for InertiaConfiguration {
    fn default() -> Self {
        Self {
            mass_g: 1000.0,
            center_of_mass_offset_mm: 100.0,
            moment_of_inertia_kgm2: [0.0; 3],
        }
    }
}

#[derive(Clone, PartialEq, Serialize, Deserialize)]
pub enum Command {
    Reset,
    SetWifi {
        ssid: String,
        password: String,
    },
    SetLedColor {
        r: u8,
        g: u8,
        b: u8,
    },
    TestServo {
        servo_id: u8,
        start: f32,
        end: f32,
    },
    DetectServos,
    SetServoConfiguration {
        axis: ServoAxis,
        configuration: ServoConfiguration,
    },
    CaptureServoZero {
        axis: ServoAxis,
    },
    SetServoEnabled {
        axis: ServoAxis,
        enabled: bool,
    },
    SetServoPosition {
        axis: ServoAxis,
        position: f32,
    },
    StartServoPerformanceTest {
        axis: ServoAxis,
        configuration: ServoConfiguration,
    },
    AssignServoDevice {
        axis: ServoAxis,
        device: ServoDeviceId,
    },
    SaveServoConfigurations,
    SetServoOrientationCheck {
        running: bool,
    },
    StartInertiaCapture,
    SetInertiaConfiguration {
        configuration: InertiaConfiguration,
    },
    SaveInertiaConfiguration {
        configuration: InertiaConfiguration,
    },
    SetSimulationConfiguration {
        configuration: SimulationConfiguration,
    },
    SaveSimulationConfiguration {
        configuration: SimulationConfiguration,
    },
    StartHilSimulation { configuration: SimulationConfiguration },
}

#[derive(Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TestData {
    pub data: Vec<(u16, u16)>,
}
